{
  "name": "SemanticModel",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "expressions": [
      {
        "name": "p_DataPath",
        "kind": "m",
        "expression": [
          "\"C:\\\\Users\\\\apdar\\\\github-portfolio\\\\saas-financial-kpis\\\\data\\\\superstore.csv\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "src_superstore",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Csv.Document(",
          "        File.Contents(p_DataPath),",
          "        [Delimiter = \",\", Columns = 21, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
          "    ),",
          "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
          "    // Types pinned to en-US: the CSV uses ISO dates and a dot decimal",
          "    // separator, which a pt-BR locale would otherwise misread.",
          "    Typed = Table.TransformColumnTypes(",
          "        Promoted,",
          "        {",
          "            {\"Row ID\", Int64.Type}, {\"Order ID\", type text},",
          "            {\"Order Date\", type date}, {\"Ship Date\", type date},",
          "            {\"Ship Mode\", type text}, {\"Customer ID\", type text},",
          "            {\"Customer Name\", type text}, {\"Segment\", type text},",
          "            {\"Country\", type text}, {\"City\", type text},",
          "            {\"State\", type text}, {\"Postal Code\", type text},",
          "            {\"Region\", type text}, {\"Product ID\", type text},",
          "            {\"Category\", type text}, {\"Sub-Category\", type text},",
          "            {\"Product Name\", type text}, {\"Sales\", type number},",
          "            {\"Quantity\", Int64.Type}, {\"Discount\", type number},",
          "            {\"Profit\", type number}",
          "        },",
          "        \"en-US\"",
          "    ),",
          "    // Loaded into memory once - five downstream queries read this.",
          "    Buffered = Table.Buffer(Typed)",
          "in",
          "    Buffered"
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "dim_date",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "yyyy\\-mm\\-dd",
            "isKey": true
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "Month Number"
          },
          {
            "name": "Year Month",
            "dataType": "string",
            "sourceColumn": "Year Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "Year Month Sort"
          },
          {
            "name": "Year Month Sort",
            "dataType": "int64",
            "sourceColumn": "Year Month Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "Quarter Number"
          },
          {
            "name": "Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Day of Week",
            "dataType": "string",
            "sourceColumn": "Day of Week",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    MinDate   = List.Min(src_superstore[Order Date]),",
                "    MaxDate   = List.Max(src_superstore[Ship Date]),",
                "    StartDate = #date(Date.Year(MinDate), 1, 1),",
                "    EndDate   = #date(Date.Year(MaxDate), 12, 31),",
                "    DayCount  = Duration.Days(EndDate - StartDate) + 1,",
                "    DateList  = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),",
                "    ToTable   = Table.FromList(DateList, Splitter.SplitByNothing(), {\"Date\"}, null, ExtraValues.Error),",
                "    TypedDate = Table.TransformColumnTypes(ToTable, {{\"Date\", type date}}),",
                "    AddYear        = Table.AddColumn(TypedDate,      \"Year\",            each Date.Year([Date]), Int64.Type),",
                "    AddMonthNo     = Table.AddColumn(AddYear,        \"Month Number\",    each Date.Month([Date]), Int64.Type),",
                "    AddMonth       = Table.AddColumn(AddMonthNo,     \"Month\",           each Date.ToText([Date], \"MMM\", \"en-US\"), type text),",
                "    AddYearMonth   = Table.AddColumn(AddMonth,       \"Year Month\",      each Date.ToText([Date], \"yyyy-MM\"), type text),",
                "    AddYearMonthNo = Table.AddColumn(AddYearMonth,   \"Year Month Sort\", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),",
                "    AddQuarter     = Table.AddColumn(AddYearMonthNo, \"Quarter\",         each \"Q\" & Text.From(Date.QuarterOfYear([Date])), type text),",
                "    AddQuarterNo   = Table.AddColumn(AddQuarter,     \"Quarter Number\",  each Date.QuarterOfYear([Date]), Int64.Type),",
                "    AddDayOfWeek   = Table.AddColumn(AddQuarterNo,   \"Day of Week\",     each Date.ToText([Date], \"ddd\", \"en-US\"), type text)",
                "in",
                "    AddDayOfWeek"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "dataCategory": "Time"
      },
      {
        "name": "dim_customer",
        "columns": [
          {
            "name": "customer_id",
            "dataType": "string",
            "sourceColumn": "customer_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "customer_name",
            "dataType": "string",
            "sourceColumn": "customer_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "segment",
            "dataType": "string",
            "sourceColumn": "segment",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "first_order_date",
            "dataType": "dateTime",
            "sourceColumn": "first_order_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "yyyy\\-mm\\-dd"
          },
          {
            "name": "last_order_date",
            "dataType": "dateTime",
            "sourceColumn": "last_order_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "yyyy\\-mm\\-dd"
          },
          {
            "name": "lifetime_revenue",
            "dataType": "double",
            "sourceColumn": "lifetime_revenue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "lifetime_profit",
            "dataType": "double",
            "sourceColumn": "lifetime_profit",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "order_count",
            "dataType": "int64",
            "sourceColumn": "order_count",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "customer_value_tier",
            "dataType": "string",
            "sourceColumn": "customer_value_tier",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "customer_value_tier_sort"
          },
          {
            "name": "customer_value_tier_sort",
            "dataType": "int64",
            "sourceColumn": "customer_value_tier_sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "lifetime_margin_pct",
            "dataType": "double",
            "sourceColumn": "lifetime_margin_pct",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0%"
          },
          {
            "name": "tenure_days",
            "dataType": "int64",
            "sourceColumn": "tenure_days",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "dim_customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Grouped = Table.Group(",
                "        src_superstore,",
                "        {\"Customer ID\"},",
                "        {",
                "            {\"customer_name\",     each List.First([Customer Name]), type text},",
                "            {\"segment\",           each List.First([Segment]), type text},",
                "            {\"first_order_date\",  each List.Min([Order Date]), type date},",
                "            {\"last_order_date\",   each List.Max([Order Date]), type date},",
                "            {\"lifetime_revenue\",  each List.Sum([Sales]), type number},",
                "            {\"lifetime_profit\",   each List.Sum([Profit]), type number},",
                "            {\"order_count\",       each List.Count(List.Distinct([Order ID])), Int64.Type}",
                "        }",
                "    ),",
                "    Renamed = Table.RenameColumns(Grouped, {{\"Customer ID\", \"customer_id\"}}),",
                "    // Thresholds are a business rule, written here so they are easy to see",
                "    // and easy to change.",
                "    AddTier = Table.AddColumn(Renamed, \"customer_value_tier\",",
                "        each if [lifetime_revenue] >= 5000 then \"High Value\"",
                "             else if [lifetime_revenue] >= 1500 then \"Mid Value\"",
                "             else \"Low Value\", type text),",
                "    AddTierSort = Table.AddColumn(AddTier, \"customer_value_tier_sort\",",
                "        each if [customer_value_tier] = \"High Value\" then 1",
                "             else if [customer_value_tier] = \"Mid Value\" then 2",
                "             else 3, Int64.Type),",
                "    AddMargin = Table.AddColumn(AddTierSort, \"lifetime_margin_pct\",",
                "        each if [lifetime_revenue] = 0 then 0 else [lifetime_profit] / [lifetime_revenue], type number),",
                "    AddTenure = Table.AddColumn(AddMargin, \"tenure_days\",",
                "        each Duration.Days([last_order_date] - [first_order_date]), Int64.Type)",
                "in",
                "    AddTenure"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_product",
        "columns": [
          {
            "name": "product_id",
            "dataType": "string",
            "sourceColumn": "product_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "product_name",
            "dataType": "string",
            "sourceColumn": "product_name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "category",
            "dataType": "string",
            "sourceColumn": "category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sub_category",
            "dataType": "string",
            "sourceColumn": "sub_category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "total_revenue",
            "dataType": "double",
            "sourceColumn": "total_revenue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "total_profit",
            "dataType": "double",
            "sourceColumn": "total_profit",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "product_margin_pct",
            "dataType": "double",
            "sourceColumn": "product_margin_pct",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "dim_product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Grouped = Table.Group(",
                "        src_superstore,",
                "        {\"Product ID\"},",
                "        {",
                "            {\"product_name\",  each List.First([Product Name]), type text},",
                "            {\"category\",      each List.First([Category]), type text},",
                "            // #\"...\" is required: a field name with a hyphen is not a valid",
                "            // M identifier, so [Sub-Category] fails to parse.",
                "            {\"sub_category\",  each List.First([#\"Sub-Category\"]), type text},",
                "            {\"total_revenue\", each List.Sum([Sales]), type number},",
                "            {\"total_profit\",  each List.Sum([Profit]), type number}",
                "        }",
                "    ),",
                "    Renamed = Table.RenameColumns(Grouped, {{\"Product ID\", \"product_id\"}}),",
                "    AddMargin = Table.AddColumn(Renamed, \"product_margin_pct\",",
                "        each if [total_revenue] = 0 then 0 else [total_profit] / [total_revenue], type number)",
                "in",
                "    AddMargin"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_geography",
        "columns": [
          {
            "name": "country",
            "dataType": "string",
            "sourceColumn": "country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "state",
            "dataType": "string",
            "sourceColumn": "state",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince"
          },
          {
            "name": "city",
            "dataType": "string",
            "sourceColumn": "city",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City"
          },
          {
            "name": "postal_code",
            "dataType": "string",
            "sourceColumn": "postal_code",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "PostalCode"
          },
          {
            "name": "geo_key",
            "dataType": "string",
            "sourceColumn": "geo_key",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "dim_geography",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Selected = Table.SelectColumns(src_superstore, {\"Country\", \"Region\", \"State\", \"City\", \"Postal Code\"}),",
                "    Distinct = Table.Distinct(Selected),",
                "    // Surrogate key built the same way in fact_orders, so the join is exact.",
                "    AddKey = Table.AddColumn(Distinct, \"geo_key\",",
                "        each Text.Combine({[Country], [State], [City], [Postal Code]}, \"|\"), type text),",
                "    Renamed = Table.RenameColumns(AddKey, {",
                "        {\"Country\", \"country\"}, {\"Region\", \"region\"},",
                "        {\"State\", \"state\"}, {\"City\", \"city\"}, {\"Postal Code\", \"postal_code\"}})",
                "in",
                "    Renamed"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_orders",
        "columns": [
          {
            "name": "order_id",
            "dataType": "string",
            "sourceColumn": "order_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "order_date",
            "dataType": "dateTime",
            "sourceColumn": "order_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "yyyy\\-mm\\-dd"
          },
          {
            "name": "ship_date",
            "dataType": "dateTime",
            "sourceColumn": "ship_date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "yyyy\\-mm\\-dd"
          },
          {
            "name": "ship_mode",
            "dataType": "string",
            "sourceColumn": "ship_mode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "customer_id",
            "dataType": "string",
            "sourceColumn": "customer_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "product_id",
            "dataType": "string",
            "sourceColumn": "product_id",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "geo_key",
            "dataType": "string",
            "sourceColumn": "geo_key",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "sales",
            "dataType": "double",
            "sourceColumn": "sales",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "quantity",
            "dataType": "int64",
            "sourceColumn": "quantity",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "discount",
            "dataType": "double",
            "sourceColumn": "discount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0%"
          },
          {
            "name": "profit",
            "dataType": "double",
            "sourceColumn": "profit",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "days_to_ship",
            "dataType": "int64",
            "sourceColumn": "days_to_ship",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "is_profitable",
            "dataType": "boolean",
            "sourceColumn": "is_profitable",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"TRUE\";;\"FALSE\""
          },
          {
            "name": "margin_pct",
            "dataType": "double",
            "sourceColumn": "margin_pct",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0%"
          },
          {
            "name": "discount_tier",
            "dataType": "string",
            "sourceColumn": "discount_tier",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "discount_tier_sort"
          },
          {
            "name": "discount_tier_sort",
            "dataType": "int64",
            "sourceColumn": "discount_tier_sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "fact_orders",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Selected = Table.SelectColumns(src_superstore, {",
                "        \"Order ID\", \"Order Date\", \"Ship Date\", \"Ship Mode\", \"Customer ID\",",
                "        \"Product ID\", \"Country\", \"State\", \"City\", \"Postal Code\",",
                "        \"Sales\", \"Quantity\", \"Discount\", \"Profit\"}),",
                "    AddGeoKey = Table.AddColumn(Selected, \"geo_key\",",
                "        each Text.Combine({[Country], [State], [City], [Postal Code]}, \"|\"), type text),",
                "    AddDaysToShip = Table.AddColumn(AddGeoKey, \"days_to_ship\",",
                "        each Duration.Days([Ship Date] - [Order Date]), Int64.Type),",
                "    AddIsProfitable = Table.AddColumn(AddDaysToShip, \"is_profitable\",",
                "        each [Profit] > 0, type logical),",
                "    AddMarginPct = Table.AddColumn(AddIsProfitable, \"margin_pct\",",
                "        each if [Sales] = 0 then 0 else [Profit] / [Sales], type number),",
                "    AddDiscountTier = Table.AddColumn(AddMarginPct, \"discount_tier\",",
                "        each if [Discount] = 0 then \"No discount\"",
                "             else if [Discount] <= 0.1 then \"1-10%\"",
                "             else if [Discount] <= 0.2 then \"11-20%\"",
                "             else if [Discount] <= 0.3 then \"21-30%\"",
                "             else \"Over 30%\", type text),",
                "    AddDiscountTierSort = Table.AddColumn(AddDiscountTier, \"discount_tier_sort\",",
                "        each if [Discount] = 0 then 0",
                "             else if [Discount] <= 0.1 then 1",
                "             else if [Discount] <= 0.2 then 2",
                "             else if [Discount] <= 0.3 then 3",
                "             else 4, Int64.Type),",
                "    Renamed = Table.RenameColumns(AddDiscountTierSort, {",
                "        {\"Order ID\", \"order_id\"}, {\"Order Date\", \"order_date\"}, {\"Ship Date\", \"ship_date\"},",
                "        {\"Ship Mode\", \"ship_mode\"}, {\"Customer ID\", \"customer_id\"}, {\"Product ID\", \"product_id\"},",
                "        {\"Sales\", \"sales\"}, {\"Quantity\", \"quantity\"}, {\"Discount\", \"discount\"}, {\"Profit\", \"profit\"}}),",
                "    Final = Table.SelectColumns(Renamed, {",
                "        \"order_id\", \"order_date\", \"ship_date\", \"ship_mode\", \"customer_id\", \"product_id\",",
                "        \"geo_key\", \"sales\", \"quantity\", \"discount\", \"profit\",",
                "        \"days_to_ship\", \"is_profitable\", \"margin_pct\", \"discount_tier\", \"discount_tier_sort\"})",
                "in",
                "    Final"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "measures": [
          {
            "name": "Total Revenue",
            "expression": "SUM(fact_orders[sales])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "1 Core"
          },
          {
            "name": "Total Profit",
            "expression": "SUM(fact_orders[profit])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "1 Core"
          },
          {
            "name": "Profit Margin %",
            "expression": "DIVIDE([Total Profit], [Total Revenue], 0)",
            "formatString": "0.0%",
            "displayFolder": "1 Core"
          },
          {
            "name": "Total Orders",
            "expression": "DISTINCTCOUNT(fact_orders[order_id])",
            "formatString": "#,0",
            "displayFolder": "1 Core"
          },
          {
            "name": "Total Customers",
            "expression": "DISTINCTCOUNT(fact_orders[customer_id])",
            "formatString": "#,0",
            "displayFolder": "1 Core"
          },
          {
            "name": "Avg Order Value",
            "expression": "DIVIDE([Total Revenue], [Total Orders], 0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "1 Core"
          },
          {
            "name": "Total Quantity",
            "expression": "SUM(fact_orders[quantity])",
            "formatString": "#,0",
            "displayFolder": "1 Core"
          },
          {
            "name": "Avg Discount",
            "expression": "AVERAGE(fact_orders[discount])",
            "formatString": "0.0%",
            "displayFolder": "1 Core"
          },
          {
            "name": "Revenue YoY %",
            "expression": [
              "VAR CurrentRevenue = [Total Revenue]",
              "VAR PriorRevenue =",
              "    CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(dim_date[Date]))",
              "RETURN",
              "    IF(",
              "        ISBLANK(PriorRevenue) || PriorRevenue = 0,",
              "        BLANK(),",
              "        DIVIDE(CurrentRevenue - PriorRevenue, PriorRevenue)",
              "    )"
            ],
            "formatString": "0.0%",
            "displayFolder": "2 Time Intelligence"
          },
          {
            "name": "Revenue YoY Abs",
            "expression": [
              "VAR PriorRevenue =",
              "    CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(dim_date[Date]))",
              "RETURN [Total Revenue] - PriorRevenue"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "2 Time Intelligence"
          },
          {
            "name": "Revenue Rolling 3M",
            "expression": [
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESINPERIOD(dim_date[Date], LASTDATE(dim_date[Date]), -3, MONTH)",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "2 Time Intelligence"
          },
          {
            "name": "Revenue YTD",
            "expression": "CALCULATE([Total Revenue], DATESYTD(dim_date[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "2 Time Intelligence"
          },
          {
            "name": "Revenue YTD Prior Year",
            "expression": "CALCULATE([Revenue YTD], SAMEPERIODLASTYEAR(dim_date[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "2 Time Intelligence"
          },
          {
            "name": "Revenue YTD vs PY %",
            "expression": "DIVIDE([Revenue YTD] - [Revenue YTD Prior Year], [Revenue YTD Prior Year], BLANK())",
            "formatString": "0.0%",
            "displayFolder": "2 Time Intelligence"
          },
          {
            "name": "Revenue % of Total",
            "expression": "DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALLSELECTED()), 0)",
            "formatString": "0.0%",
            "displayFolder": "3 Dynamic"
          },
          {
            "name": "Product Revenue Rank",
            "expression": [
              "IF(",
              "    HASONEVALUE(dim_product[product_name]),",
              "    RANKX(ALLSELECTED(dim_product[product_name]), [Total Revenue], , DESC, DENSE)",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "3 Dynamic"
          },
          {
            "name": "SubCategory Revenue Rank",
            "expression": [
              "IF(",
              "    HASONEVALUE(dim_product[sub_category]),",
              "    RANKX(ALLSELECTED(dim_product[sub_category]), [Total Revenue], , DESC, DENSE)",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "3 Dynamic"
          },
          {
            "name": "Revenue % of Category",
            "expression": [
              "DIVIDE(",
              "    [Total Revenue],",
              "    CALCULATE([Total Revenue], ALLEXCEPT(dim_product, dim_product[category])),",
              "    0",
              ")"
            ],
            "formatString": "0.0%",
            "displayFolder": "3 Dynamic"
          },
          {
            "name": "Profit Margin vs Category Avg",
            "expression": [
              "VAR CurrentMargin = [Profit Margin %]",
              "VAR CategoryAvgMargin =",
              "    CALCULATE([Profit Margin %], ALLEXCEPT(dim_product, dim_product[category]))",
              "RETURN CurrentMargin - CategoryAvgMargin"
            ],
            "formatString": "0.0%",
            "displayFolder": "3 Dynamic"
          },
          {
            "name": "Avg Customer LTV",
            "expression": "AVERAGEX(VALUES(dim_customer[customer_id]), CALCULATE([Total Revenue]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "4 Customer"
          },
          {
            "name": "Revenue per Customer",
            "expression": "DIVIDE([Total Revenue], [Total Customers], 0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "4 Customer"
          },
          {
            "name": "High Value Revenue %",
            "expression": [
              "DIVIDE(",
              "    CALCULATE([Total Revenue], dim_customer[customer_value_tier] = \"High Value\"),",
              "    [Total Revenue],",
              "    0",
              ")"
            ],
            "formatString": "0.0%",
            "displayFolder": "4 Customer"
          },
          {
            "name": "Loss-Making Orders",
            "expression": "CALCULATE([Total Orders], fact_orders[is_profitable] = FALSE())",
            "formatString": "#,0",
            "displayFolder": "4 Customer"
          },
          {
            "name": "Loss-Making Orders %",
            "expression": "DIVIDE([Loss-Making Orders], [Total Orders], 0)",
            "formatString": "0.0%",
            "displayFolder": "4 Customer"
          },
          {
            "name": "Avg Days to Ship",
            "expression": "AVERAGEX(VALUES(fact_orders[order_id]), CALCULATE(MAX(fact_orders[days_to_ship])))",
            "formatString": "0.0",
            "displayFolder": "4 Customer"
          },
          {
            "name": "New Customers",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(dim_customer[customer_id]),",
              "    FILTER(",
              "        dim_customer,",
              "        dim_customer[first_order_date] >= MIN(dim_date[Date])",
              "            && dim_customer[first_order_date] <= MAX(dim_date[Date])",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "4 Customer"
          },
          {
            "name": "New Customers %",
            "expression": "DIVIDE([New Customers], [Total Customers], 0)",
            "formatString": "0.0%",
            "displayFolder": "4 Customer"
          },
          {
            "name": "Revenue Lost to Discount",
            "expression": "SUMX(fact_orders, fact_orders[sales] * fact_orders[discount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "5 Discount"
          },
          {
            "name": "Revenue at Full Price",
            "expression": "SUMX(fact_orders, fact_orders[sales] + (fact_orders[sales] * fact_orders[discount]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "5 Discount"
          },
          {
            "name": "Discount Impact on Profit",
            "expression": "SUMX(fact_orders, fact_orders[sales] * fact_orders[discount] * fact_orders[margin_pct])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "5 Discount"
          },
          {
            "name": "Profit if No Discount",
            "expression": "[Total Profit] - [Discount Impact on Profit]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "5 Discount"
          },
          {
            "name": "Loss-Making Revenue",
            "expression": "CALCULATE([Total Revenue], fact_orders[is_profitable] = FALSE())",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "5 Discount"
          },
          {
            "name": "Weighted Avg Discount",
            "expression": [
              "DIVIDE(",
              "    SUMX(fact_orders, fact_orders[discount] * fact_orders[sales]),",
              "    [Total Revenue],",
              "    0",
              ")"
            ],
            "formatString": "0.0%",
            "displayFolder": "5 Discount"
          },
          {
            "name": "Selected Year Label",
            "expression": [
              "IF(",
              "    HASONEVALUE(dim_date[Year]),",
              "    \"Year \" & SELECTEDVALUE(dim_date[Year]),",
              "    \"All Years\"",
              ")"
            ],
            "displayFolder": "7 Labels"
          },
          {
            "name": "Revenue KPI Status",
            "expression": [
              "VAR Growth = [Revenue YoY %]",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        ISBLANK(Growth),  \"—\",",
              "        Growth >= 0.1,    \"▲ Strong Growth\",",
              "        Growth >= 0,      \"▲ Growth\",",
              "        Growth >= -0.1,   \"▼ Decline\",",
              "        \"▼ Strong Decline\"",
              "    )"
            ],
            "displayFolder": "7 Labels"
          },
          {
            "name": "Profit Margin Status",
            "expression": [
              "VAR Margin = [Profit Margin %]",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        Margin >= 0.20, \"● Excellent\",",
              "        Margin >= 0.10, \"● Good\",",
              "        Margin >= 0,    \"● Low\",",
              "        \"● Negative\"",
              "    )"
            ],
            "displayFolder": "7 Labels"
          },
          {
            "name": "Simulated Revenue",
            "expression": [
              "SUMX(",
              "    fact_orders,",
              "    VAR OriginalDiscount = fact_orders[discount]",
              "    VAR ReducedDiscount = MAX(0, OriginalDiscount - [Discount Reduction Value])",
              "    VAR OriginalSales = fact_orders[sales]",
              "    VAR SimulatedSales = OriginalSales * (1 + OriginalDiscount) / (1 + ReducedDiscount)",
              "    RETURN SimulatedSales",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "6 What-If"
          },
          {
            "name": "Revenue Uplift",
            "expression": "[Simulated Revenue] - [Total Revenue]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "6 What-If"
          },
          {
            "name": "Simulated Profit Margin %",
            "expression": [
              "VAR SimulatedProfit =",
              "    SUMX(",
              "        fact_orders,",
              "        VAR OriginalDiscount = fact_orders[discount]",
              "        VAR ReducedDiscount = MAX(0, OriginalDiscount - [Discount Reduction Value])",
              "        VAR OriginalSales = fact_orders[sales]",
              "        VAR SimulatedSales = OriginalSales * (1 + OriginalDiscount) / (1 + ReducedDiscount)",
              "        VAR MarginGain = (SimulatedSales - OriginalSales) * fact_orders[margin_pct]",
              "        RETURN fact_orders[profit] + MarginGain",
              "    )",
              "RETURN DIVIDE(SimulatedProfit, [Simulated Revenue], 0)"
            ],
            "formatString": "0.0%",
            "displayFolder": "6 What-If"
          }
        ]
      },
      {
        "name": "Discount Reduction",
        "columns": [
          {
            "name": "Discount Reduction",
            "dataType": "double",
            "formatString": "0.0%",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Discount Reduction",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(0, 0.5, 0.05)"
            }
          }
        ],
        "measures": [
          {
            "name": "Discount Reduction Value",
            "expression": "SELECTEDVALUE('Discount Reduction'[Discount Reduction], 0)",
            "formatString": "0.0%"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "discount_reduction_param"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_date_order",
        "fromTable": "fact_orders",
        "fromColumn": "order_date",
        "toTable": "dim_date",
        "toColumn": "Date"
      },
      {
        "name": "rel_date_ship",
        "fromTable": "fact_orders",
        "fromColumn": "ship_date",
        "toTable": "dim_date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "rel_customer",
        "fromTable": "fact_orders",
        "fromColumn": "customer_id",
        "toTable": "dim_customer",
        "toColumn": "customer_id"
      },
      {
        "name": "rel_product",
        "fromTable": "fact_orders",
        "fromColumn": "product_id",
        "toTable": "dim_product",
        "toColumn": "product_id"
      },
      {
        "name": "rel_geography",
        "fromTable": "fact_orders",
        "fromColumn": "geo_key",
        "toTable": "dim_geography",
        "toColumn": "geo_key"
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"p_DataPath\", \"src_superstore\", \"dim_date\", \"dim_customer\", \"dim_product\", \"dim_geography\", \"fact_orders\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}